# Generated by Django 4.1.6 on 2023-03-08 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_skill_description_experience_education"),
    ]

    operations = [
        migrations.RenameField(
            model_name="education",
            old_name="current",
            new_name="is_current",
        ),
        migrations.RenameField(
            model_name="experience",
            old_name="to_date",
            new_name="date_to",
        ),
        migrations.RenameField(
            model_name="experience",
            old_name="current",
            new_name="is_current",
        ),
    ]
