# Generated by Django 4.1.6 on 2023-03-08 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_rename_current_education_is_current_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="experience",
            old_name="date_to",
            new_name="to_date",
        ),
    ]
