# Generated by Django 4.1.6 on 2023-04-16 10:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_message"),
    ]

    operations = [
        migrations.CreateModel(
            name="Follower",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "follower_profile",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="following",
                        to="users.profile",
                    ),
                ),
                (
                    "following_profile",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="followers",
                        to="users.profile",
                    ),
                ),
            ],
            options={
                "unique_together": {("follower_profile", "following_profile")},
            },
        ),
    ]
