# Generated by Django 4.1.6 on 2023-04-16 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_follower"),
    ]

    operations = [
        migrations.RenameField(
            model_name="follower",
            old_name="follower_profile",
            new_name="receiver_profile",
        ),
        migrations.RenameField(
            model_name="follower",
            old_name="following_profile",
            new_name="sender_profile",
        ),
        migrations.AlterUniqueTogether(
            name="follower",
            unique_together={("sender_profile", "receiver_profile")},
        ),
    ]
