# Generated by Django 4.1.6 on 2023-04-16 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_rename_follower_profile_follower_receiver_profile_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="experience",
            name="following",
            field=models.ManyToManyField(
                blank=True,
                related_name="followers",
                through="users.Follower",
                to="users.experience",
            ),
        ),
    ]
