# Generated by Django 4.1.6 on 2023-04-16 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_experience_following"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="experience",
            name="following",
        ),
        migrations.AddField(
            model_name="profile",
            name="following",
            field=models.ManyToManyField(
                blank=True,
                related_name="followers",
                through="users.Follower",
                to="users.profile",
            ),
        ),
        migrations.AlterField(
            model_name="follower",
            name="receiver_profile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="received_follows",
                to="users.profile",
            ),
        ),
        migrations.AlterField(
            model_name="follower",
            name="sender_profile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sent_follows",
                to="users.profile",
            ),
        ),
    ]
