# Generated by Django 4.1.6 on 2023-04-16 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_remove_experience_following_profile_following_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="is_online",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
