# Generated by Django 4.1.6 on 2023-04-18 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0013_news"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Message",
        ),
    ]
