# Generated by Django 4.1.6 on 2023-03-06 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "projects",
            "0002_tag_project_votes_count_project_votes_ratio_review_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="project_image",
            field=models.ImageField(
                blank=True, default="defaultProject.jpg", null=True, upload_to=""
            ),
        ),
    ]
