# Generated by Django 4.1.6 on 2023-04-02 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0005_alter_project_options_review_owner_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={
                "ordering": ["-votes_count", "-votes_ratio", "title", "-created_at"]
            },
        ),
    ]
