# Generated by Django 4.1.7 on 2023-03-06 21:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profil",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.CharField(max_length=100)),
                ("bio", models.TextField(max_length=300)),
                ("location", models.CharField(max_length=50)),
                ("linkedin_link", models.CharField(max_length=50, null=True)),
                ("github_link", models.CharField(max_length=50, null=True)),
                ("twitter_link", models.CharField(max_length=50, null=True)),
                ("youtube_link", models.CharField(max_length=50, null=True)),
                ("website_link", models.CharField(max_length=50, null=True)),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
